apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    eks.amazonaws.com/nodegroup: Mid-Size-Node-Group-8Gig
    io.kompose.service: elasticsearch-data
  name: elasticsearch-data
  namespace: otobo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
