apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: mid
    eks.amazonaws.com/nodegroup: Mid-Size-Node-Group-8Gig
    type: otobo-pv
    io.kompose.service: opt-otobo
  name: opt-otobo
  namespace: otobo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
