apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: otobo
  name: otobo-pv
  labels:
    type: otobo-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0f4d99fdcdf45039d
